version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: /home/ubuntu/stop_previous_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ubuntu/start_container.sh
      timeout: 300
      runas: root

