version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: /home/ec2-user/stop_previous_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ec2-user/start_container.sh
      timeout: 300
      runas: root

