version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/ec2-user
  - source: /scripts
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/stop_previous_container.sh
      timeout: 200
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 200
      runas: root

