version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: /tmp/stop_previous_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /tmp/start_container.sh
      timeout: 300
      runas: root

