version: 0.2

phases:
  install:
    commands:
      - echo "the installation phase begins"
  pre_build:
    commands:
      - echo "the prebuild phase begins"
      - npm install
  build:
    commands:
      - echo "the build phase begins"
      - echo `pwd`
      - npm run build
      - echo `ls`

  post_build:
    commands:
      - echo "the post build phase. navigating back to root path"
      # - cp  build/ ./build

artifacts:
  files:
    - build/**/*


# New Dockerization Step
post_build:
  commands:
    - echo "Building and Pushing Docker Image"
    - echo "Logging into Amazon ECR"
    - $(aws ecr get-login --no-include-email --region your-region)
    - docker build -t backend-img  .
    - docker tag backend-img:latest public.ecr.aws/e1l0d8t8/saket-repo/backend-img:latest
    - docker push public.ecr.aws/e1l0d8t8/saket-repo/backend-img:latest


# New S3 Upload Step
artifacts:
  files:
    - build/**/*
  discard-paths: yes
